# Generated by Django 5.2.5 on 2026-01-20 12:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        max_length=256, verbose_name='Наименование'
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        max_length=56, unique=True, verbose_name='Слаг'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'client_name',
                    models.CharField(max_length=128, verbose_name='Клиент'),
                ),
                (
                    'mobile_phone',
                    models.CharField(
                        help_text='Введите номер телефона в формате +79998887766',
                        max_length=16,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code='invalid_phone',
                                message="Номер телефона должен начинаться с '+7' и содержать 11 цифр",
                                regex='^\\+7\\d{10}$',
                            )
                        ],
                        verbose_name='Мобильный телефон',
                    ),
                ),
                (
                    'entity_type',
                    models.CharField(
                        choices=[('FL', 'физ'), ('UL', 'юр')],
                        default='FL',
                        max_length=2,
                        verbose_name='Тип лица',
                    ),
                ),
                (
                    'company',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=256,
                        verbose_name='Название компании',
                    ),
                ),
                (
                    'address',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=256,
                        verbose_name='Адрес',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ('company__gt', ''), ('entity_type', 'UL')
                            ),
                            models.Q(('entity_type', 'UL'), _negated=True),
                            _connector='OR',
                        ),
                        name='company_required_for_UL',
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'number',
                    models.PositiveIntegerField(
                        editable=False,
                        unique=True,
                        verbose_name='Номер заказа',
                    ),
                ),
                (
                    'create',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'accepted_equipment',
                    models.CharField(
                        help_text='Наименование оборудования',
                        max_length=256,
                        verbose_name='Принятое оборудование',
                    ),
                ),
                (
                    'detail',
                    models.CharField(
                        help_text='Описание неисправности',
                        max_length=512,
                        verbose_name='Детали заказа',
                    ),
                ),
                (
                    'advance',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal('0.00')
                            )
                        ],
                        verbose_name='Аванс',
                    ),
                ),
                (
                    'paid',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal('0.00')
                            )
                        ],
                        verbose_name='Оплачено (доплата)',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('in_working', 'в работе'),
                            ('under_approval', 'на согласовании'),
                            ('waiting_part', 'ожидает запчасть'),
                            ('in_service', 'находится в сервисном'),
                            ('ready_pickup', 'готово к выдаче'),
                            ('completed', 'выполнено'),
                            ('not_relevant', 'не актуально'),
                        ],
                        db_index=True,
                        default='in_working',
                        max_length=56,
                        verbose_name='Статус заказа',
                    ),
                ),
                (
                    'client',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='orders',
                        to='crm.client',
                        verbose_name='Клиент',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'create',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'store',
                    models.CharField(
                        max_length=256, verbose_name='Наименование магазина'
                    ),
                ),
                (
                    'detail',
                    models.CharField(
                        max_length=256, verbose_name='Детали покупки'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('delivery_expected', 'ожидается поставка'),
                            ('received', 'получено'),
                            ('installed', 'установлено'),
                        ],
                        db_index=True,
                        default='delivery_expected',
                        max_length=56,
                        verbose_name='Статус покупки',
                    ),
                ),
                (
                    'order',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='purchases',
                        to='crm.order',
                        verbose_name='Номер заказа',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'service_name',
                    models.CharField(
                        max_length=128,
                        unique=True,
                        verbose_name='Наименование услуги',
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal('0.00')
                            )
                        ],
                        verbose_name='Базовая стоимость',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='services',
                        to='crm.category',
                        verbose_name='Категория',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('service_name',),
            },
        ),
        migrations.CreateModel(
            name='ServiceInOrder',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal('0.00')
                            )
                        ],
                        verbose_name='Стоимость услуги в заказе',
                    ),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='service_lines',
                        to='crm.order',
                        verbose_name='Заказ',
                    ),
                ),
                (
                    'service',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='order_lines',
                        to='crm.service',
                        verbose_name='Услуга',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Услуга в заказе',
                'verbose_name_plural': 'Услуги в заказах',
                'ordering': ('order', 'service'),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(
                blank=True,
                related_name='orders',
                through='crm.ServiceInOrder',
                to='crm.service',
                verbose_name='Услуги',
            ),
        ),
        migrations.AddConstraint(
            model_name='serviceinorder',
            constraint=models.UniqueConstraint(
                fields=('order', 'service'), name='uniq_service_per_order'
            ),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(
                condition=models.Q(('accepted_equipment', ''), _negated=True),
                name='order_accepted_equipment_not_empty',
            ),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(
                condition=models.Q(('detail', ''), _negated=True),
                name='order_detail_not_empty',
            ),
        ),
    ]
