# Generated by Django 5.2.5 on 2026-01-20 18:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='services_total_override',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Можно изменить вручную (скидка/коррекция).',
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal('0.00'))
                ],
                verbose_name='Стоимость услуг',
            ),
        ),
    ]
