# Generated by Django 5.2.5 on 2026-01-21 13:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_order_services_total_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='accepted_equipment',
            field=models.CharField(
                max_length=256, verbose_name='Принятое оборудование'
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='detail',
            field=models.CharField(
                max_length=512, verbose_name='Детали заказа'
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='services_total_override',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Можно изменить вручную (скидка/включить стоимость товара)',
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal('0.00'))
                ],
                verbose_name='Стоимость услуг',
            ),
        ),
    ]
