# Generated by Django 5.2.5 on 2026-01-22 10:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'crm',
            '0003_alter_order_accepted_equipment_alter_order_detail_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cost',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal('0.00'))
                ],
                verbose_name='Стоимость покупки',
            ),
        ),
    ]
