# Generated by Django 5.2.5 on 2026-01-26 14:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_order_services_total_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='advance',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal('0.00'))
                ],
                verbose_name='Аванс, ₽',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='detail',
            field=models.CharField(
                max_length=512, verbose_name='Описание неисправности'
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal('0.00'))
                ],
                verbose_name='Оплачено, ₽',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='services_total_override',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Можно изменить вручную (скидка)',
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal('0.00'))
                ],
                verbose_name='Услуги, ₽',
            ),
        ),
    ]
