"""Модуль с константами для приложений CRM-системы."""

COUNT_SERVICES_IN_ORDER = 10
MAX_LENGTH_ADDRESS = 256
MAX_LENGTH_COMPANY_NAME = 256
MAX_LENGTH_COMPONENT_DETAIL = 512
MAX_LENGTH_COMPONENT_FIELD = 256
MAX_LENGTH_ENTITY_TYPE = 2
MAX_LENGTH_MOBILE_PHONE = 16
MAX_LENGTH_NAME_CLIENT = 128
MAX_LENGTH_NAME_SHOP = 256
MAX_LENGTH_OF_DETAIL_SHOP = 256
MAX_LENGTH_OF_NAME_CATEGORY = 256
MAX_LENGTH_OF_NAME_SERVICE = 128
MAX_LENGTH_OF_SLUG = 56
MAX_LENGTH_ORDER_STATUS = 56
MAX_LENGTH_PURCHASE_STATUS = 56
MONEY_DECIMAL_PLACES = 2
MONEY_MAX_DIGITS = 10
ORDER_CODE_PAD = 5
ORDER_CODE_PREFIX = 'TN'
ORDER_SEQUENCE_NAME = 'order'
ORDERS_LIMIT_ON_HOMEPAGE = 15
QUANTITY_ON_PAGE = 10
SERVICES_LIMIT_ERROR = 'Можно выбрать не более %(limit)s услуг.'
SERVICES_LIMIT_ON_PAGE = 15
